base_url = "https://www.snoyman.com"
default_language = "en"
compile_sass = false
generate_feed = true
highlight_code = true
highlight_theme = "solarized-light"

taxonomies = [
  {name = "tags", paginate_by = 20},
  {name = "series", paginate_by = 20},
]

[extra]
# Put all your custom variables here
