[package]
name = "snoycron"
version = "0.1.0"
authors = ["Michael Snoyman <michael@snoyman.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
anyhow = "1.0.38"
serde = { version = "1.0.119", features = ["derive"] }
serde_yaml = "0.8.15"
semver = "0.10"
serde-xml-rs = "0.4.1"
chrono = { version = "0.4", features = ["serde"] }
