name: Build snoycron image

on:
  push:
    branches: [snoycron]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build snoycron image
        run: |
          set -eux

          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/snoycron:$GITHUB_SHA
          IMAGE_ID_LATEST=docker.pkg.github.com/${{ github.repository }}/snoycron:latest

          docker build snoycron --tag $IMAGE_ID
          docker tag $IMAGE_ID $IMAGE_ID_LATEST

          docker push $IMAGE_ID
          docker push $IMAGE_ID_LATEST
